[package]
name = "compressor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
flate2 = "1.0.24"
crc32fast = "1.3.2"
miniz_oxide = "0.6.2"
minifb = "0.23.0"